server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVER-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/omkarchaudhary/config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka